# Minimum-Variance portofolio

Assume that an investor can create a portfolio by allocating to three assets _A_, _B_ and _C_ with the following correlation matrix $\boldsymbol{C}$, vector of volatilities $\boldsymbol{v}$, and expected return vector $\boldsymbol{\mu}$

$$
\boldsymbol{C} = \begin{pmatrix} 1.0 & 0.2 & 0.15 \\
0.2 & 1.0 & 0.4 \\
0.15 & 0.4 & 1.0\end{pmatrix}
$$

and 

$$
\boldsymbol{v} = \begin{pmatrix} 0.1 \\ 0.15 \\ 0.2 \end{pmatrix}
$$


and 

$$
\boldsymbol{\mu} = \begin{pmatrix} 0.04 \\ 0.06 \\ 0.08 \end{pmatrix}
$$

In [40]:
# we only need the numpy package
import numpy as np

## Problem 1

Define the correlation matrix, covariance matrix and the vector of expected returns as `numpy` arrays

### Solution

In [41]:
# define the correlation matrix
corr_mat = np.array([[1.0, 0.2, 0.15], 
                     [0.2, 1.0, 0.4], 
                     [0.15, 0.4, 1.0]])

# define the vector of volatilities
vols = np.array([0.1, 0.15, 0.2])

# calculate the covariance matrix
cov_mat = np.diag(vols) @ corr_mat @ np.diag(vols)

# define the vector of expected returns 
mu = np.array([0.04, 0.06, 0.08])

## Problem 2

Check if the covariance matrix is postive definite. 

### Solution

We could simply check if the eigenvalues of the covariance matrix are all positive. 

In [42]:
eig_vals, _ = np.linalg.eigh(cov_mat)

In [43]:
# all eigenvalues are positive!
eig_vals

array([0.00931378, 0.01663894, 0.04654728])

## Problem 3

Consider an equally weighted portfolio $w_A = w_B = w_C = 1/3$. What is the formula for the portfolio variance using matrix notation? Calculate the portfolio standard devation for the equally weighted portfolio. Also calculate the expected return for the portfolio. 

### Solution

The portfolio variance is given by the formula 

$$
\sigma_p^2 = \mathbf{w}^\top \boldsymbol{\Sigma} \mathbf{w}
$$

In [44]:
# define the equally weighted portfolio
w_eq = np.repeat(1 / 3, 3)
w_eq

array([0.33333333, 0.33333333, 0.33333333])

In [45]:
# portfolio standard devation
std_eq = np.sqrt(w_eq @ cov_mat @ w_eq)
std_eq

0.10979779394667069

In [46]:
# expected return
mu_eq = w_eq @ mu
mu_eq

0.05999999999999999

## Problem 4

The portfolio weights $\mathbf{w} = (w_A \; \; w_B \; \; w_C)^\top$ satisfies the budget constraint $\mathbf{w}^\top \mathbf{1} =  w_A + w_B + w_C = 1$. The investor seeks to minimize the variance subject to this condition

$$
\min \mathbf{w}^\top \boldsymbol{\Sigma} \mathbf{w} \; \; \;  \text{s.t. } \mathbf{w}^\top \mathbf{1}  = 1
$$

The Lagrangian reads

$$
\mathcal{L} = \mathbf{w}^\top \boldsymbol{\Sigma} \mathbf{w} - \lambda (\mathbf{w}^\top \mathbf{1}  - 1)
$$

Deriving the FOC and solving for the optimal weights yields

$$
\mathbf{w}^* = \frac{\boldsymbol{\Sigma}^{-1} \mathbf{1}}{\mathbf{1}^\top \boldsymbol{\Sigma}^{-1} \mathbf{1}}
$$

Define a function which calculates the minimum-variance portfolio weights given a covariance matrix. Calculate the minimum-variance portfolio weights. 

### Solution 

In [47]:
def calculate_min_variance_portfolio(cov_mat: np.ndarray) -> np.ndarray:

    """
    Calculates the minimum-varance portfolio weights. 
    """
    
    num_assets = cov_mat.shape[0]
    vec_ones = np.ones(num_assets)
    
    cov_mat_inv = np.linalg.inv(cov_mat)

    w_min_var = cov_mat_inv @ vec_ones / (vec_ones @ cov_mat_inv @ vec_ones)

    return w_min_var

In [48]:
w_min_var = calculate_min_variance_portfolio(cov_mat)
w_min_var

array([0.70384615, 0.21538462, 0.08076923])